# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Server CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/master.key
          chmod 600 ~/.ssh/master.key
          cat >>~/.ssh/config <<END
          Host master
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/master.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Run Install & Build
        run: ssh master 'cd repos/Project11-B-Web-FE-Performance-Monitoring-Server && git checkout master && git pull && npm i'

      - name: Reload PM2
        run: ssh master 'pm2 start ecosystem.config.js'
